services:
  order:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: devl
      SECRETS_RABBITMQ_HOST: rabbitmq
      SECRETS_RABBITMQ_PORT: 5672
      SECRETS_RABBITMQ_USERNAME: guest
      SECRETS_RABBITMQ_PASSWORD: guest
      SECRETS_REDIS_HOST: redis
      SECRETS_REDIS_PORT: 6379
      SECRETS_MONGODB_DATABASE: admin
      SECRETS_MONGODB_HOST: mongodb
      SECRETS_MONGODB_PORT: 27017
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 1s
      retries: 5

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 3s
      timeout: 1s
      retries: 5

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 1s
      retries: 5
