spring:
  rabbitmq:
    host: ${secrets.rabbitmq.host}
    port: ${secrets.rabbitmq.port}
    username: ${secrets.rabbitmq.username}
    password: ${secrets.rabbitmq.password}
  data:
    redis:
      host: ${secrets.redis.host}
      port: ${secrets.redis.port}
    mongodb:
      database: ${secrets.mongodb.database}
      uri: ${secrets.mongodb.uri}
