spring:
  profiles:
    active: [ "local_vault", "devl" ]
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      auto-index-creation: true
springdoc:
  api-docs:
    path: /swagger-api-docs
  swagger-ui:
    path: /swagger-ui
