spring:
  application:
    name: "teste-levve-java"
  flyway:
    enabled: true
    url: ${secrets.db.jdbc_url}
    user: ${secrets.db.username}
    password: ${secrets.db.password}
    baseline-version: 0
    baselineOnMigrate: true
    locations: classpath:db/migration
  r2dbc:
    url: ${secrets.db.r2dbc_url}
    username: ${secrets.db.username}
    password: ${secrets.db.password}
  rabbitmq:
    host: ${secrets.rabbitmq.host}
    port: ${secrets.rabbitmq.port}
    username: ${secrets.rabbitmq.username}
    password: ${secrets.rabbitmq.password}
  data:
    redis:
      host: ${secrets.redis.host}
      port: ${secrets.redis.port}
    mongodb:
      database: ${secrets.mongodb.database}
      uri: ${secrets.mongodb.uri}
