spring:
  application:
    name: "teste-levva-java"
  #  profiles:
  #    active: [ "local_vault", "devl" ]
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      auto-index-creation: true # this will cause an error on app startup if the index already exists. The error does not impede the application in any way.
springdoc:
  api-docs:
    path: /swagger-api-docs
  swagger-ui:
    path: /swagger-ui
